### ISSUE TITLE
lily58 with mikoto - right display not working

### ISSUE THREAD

**Issue by SudarshanVK** [keebd/zmk-firmware#2]
Hi,

I have an issue with the lil58 and the right display not working after flashing the firmware.

Here is my `build.yaml` file contents

```
include:
  - board: mikoto@7.2
    shield: lily58_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
  - board: mikoto@7.2
    shield: lily58_right nice_view_adapter nice_view
    # snippet: studio-rpc-usb-uart
```
